<?php

return [
    'current_address' => [
        'label' => 'Current Address',
        'aliases' => [
            'current address',
            'current address check',
            'address current',
            'address - current',
            'present address',
            'present address check',
        ],
        'candidate_page' => 'contact',
        'candidate_subsection' => 'current_address',
        'allowed_section_key' => 'contact',
        'group_key' => 'ADDRESS',
        'count_applicable' => true,
    ],
    'permanent_address' => [
        'label' => 'Permanent Address',
        'aliases' => [
            'permanent address',
            'permanent address check',
            'address permanent',
            'address - permanent',
        ],
        'candidate_page' => 'contact',
        'candidate_subsection' => 'permanent_address',
        'allowed_section_key' => 'contact',
        'group_key' => 'ADDRESS',
        'count_applicable' => true,
    ],
    'education_reference' => [
        'label' => 'Education Reference',
        'aliases' => [
            'education reference',
            'academic reference',
            'college reference',
            'university reference',
            'qualification reference',
        ],
        'candidate_page' => 'reference',
        'candidate_subsection' => 'education_reference',
        'allowed_section_key' => 'reference',
        'group_key' => 'REFERENCE',
        'count_applicable' => true,
    ],
    'employment_reference' => [
        'label' => 'Employment Reference',
        'aliases' => [
            'employment reference',
            'employee reference',
            'employer reference',
            'professional reference',
            'work reference',
            'employment ref',
        ],
        'candidate_page' => 'reference',
        'candidate_subsection' => 'employment_reference',
        'allowed_section_key' => 'reference',
        'group_key' => 'REFERENCE',
        'count_applicable' => true,
    ],
    'identification' => [
        'label' => 'Identification',
        'aliases' => [
            'identification',
            'identity',
            'id verification',
            'kyc',
            'aadhaar',
            'aadhar',
            'pan',
            'passport',
            'driving licence',
            'driving license',
            'voter',
            'national id',
        ],
        'candidate_page' => 'identification',
        'candidate_subsection' => '',
        'allowed_section_key' => 'id',
        'group_key' => 'BASIC',
        'count_applicable' => true,
    ],
    'education' => [
        'label' => 'Education',
        'aliases' => [
            'education',
            'qualification',
            'degree',
            'college',
            'university',
            'highest qualification',
        ],
        'candidate_page' => 'education',
        'candidate_subsection' => '',
        'allowed_section_key' => 'education',
        'group_key' => 'EDUCATION',
        'count_applicable' => true,
    ],
    'employment' => [
        'label' => 'Employment',
        'aliases' => [
            'employment',
            'employer',
            'experience',
            'work history',
            'employer 1',
            'employer1',
        ],
        'candidate_page' => 'employment',
        'candidate_subsection' => '',
        'allowed_section_key' => 'employment',
        'group_key' => 'EDUCATION',
        'count_applicable' => true,
    ],
    'reference' => [
        'label' => 'Reference',
        'aliases' => [
            'reference',
            'referee',
            'ref check',
            'ref-check',
        ],
        'candidate_page' => 'reference',
        'candidate_subsection' => 'employment_reference',
        'allowed_section_key' => 'reference',
        'group_key' => 'REFERENCE',
        'count_applicable' => true,
    ],
    'ecourt' => [
        'label' => 'E-Court',
        'aliases' => [
            'ecourt',
            'e-court',
            'court',
            'judis',
            'judicial',
            'manupatra',
            'litigation',
        ],
        'candidate_page' => 'ecourt',
        'candidate_subsection' => '',
        'allowed_section_key' => 'ecourt',
        'group_key' => 'DB',
        'count_applicable' => true,
    ],
    'socialmedia' => [
        'label' => 'Social Media',
        'aliases' => [
            'social',
            'social media',
            'world check',
            'worldcheck',
            'linkedin',
            'facebook',
            'instagram',
            'twitter',
            'x.com',
        ],
        'candidate_page' => 'social',
        'candidate_subsection' => '',
        'allowed_section_key' => 'socialmedia',
        'group_key' => 'DB',
        'count_applicable' => true,
    ],
    'database' => [
        'label' => 'Database',
        'aliases' => [
            'database',
            'global database',
        ],
        'candidate_page' => '',
        'candidate_subsection' => '',
        'allowed_section_key' => 'database',
        'group_key' => 'DB',
        'count_applicable' => false,
    ],
];
