<?php
require 'config/db.php';
require 'api/shared/workflow_communication_service.php';
function normalize_component_key(string $value): string { $v = strtolower(trim($value)); if ($v==='identification') return 'id'; if ($v==='contact_information'||$v==='contact information') return 'contact'; if ($v==='education_details'||$v==='education details') return 'education'; if ($v==='employment_details'||$v==='employment details') return 'employment'; if ($v==='social_media'||$v==='social media') return 'socialmedia'; if ($v==='e-court'||$v==='e_court'||$v==='e court') return 'ecourt'; if ($v==='references') return 'reference'; return $v; }
function row_matches_component_scope(array $row, string $componentKey): bool { $rowKey = normalize_component_key((string)($row['component_key'] ?? '')); if ($rowKey === $componentKey) return true; return false; }
function normalize_role_key(string $role): string { $role = strtolower(trim($role)); if ($role === 'db verifier' || $role === 'db-verifier' || $role === 'db_verifier') return 'verifier'; return $role; }
function row_belongs_to_viewer_role(array $row, string $viewerRole, array $allowedThreadIds, array $allowedMessageIds): bool {
 if ($viewerRole === '') return true; $direction = strtolower(trim((string)($row['direction'] ?? ''))); $actorRole = normalize_role_key((string)($row['actor_role'] ?? '')); if ($direction === 'outgoing') return $actorRole === $viewerRole; if ($direction !== 'incoming') return true; $threadId = strtolower(trim((string)($row['thread_id'] ?? ''))); if ($threadId !== '' && isset($allowedThreadIds[$threadId])) return true; $inReplyTo = wc_norm_msg_id((string)($row['in_reply_to'] ?? '')); if ($inReplyTo !== '' && isset($allowedMessageIds[$inReplyTo])) return true; $references = wc_extract_msg_ids((string)($row['references_header'] ?? '')); foreach ($references as $refId) { if ($refId !== '' && isset($allowedMessageIds[$refId])) return true; } return false; }
$pdo=getDB(); $app='APP-20260520075926356'; $st=$pdo->prepare("SELECT communication_id, component_key, actor_role, direction, message_id, in_reply_to, references_header, thread_id, subject, sent_at FROM Vati_Payfiller_Workflow_Communications WHERE application_id=? ORDER BY communication_id ASC"); $st->execute([$app]); $rows=$st->fetchAll(PDO::FETCH_ASSOC)?:[];
foreach ([['validator','education'],['verifier','education'],['validator','contact'],['verifier','contact'],['qa','contact'],['qa','education'],['verifier','id']] as $combo) {
 [$viewerRole,$componentKey]=$combo; $data=array_values(array_filter($rows, fn($r)=>row_matches_component_scope($r,$componentKey)));
 $allowedThreadIds=[]; $allowedMessageIds=[]; foreach($data as $row){ if(strtolower(trim((string)$row['direction']))!=='outgoing') continue; if(normalize_role_key((string)$row['actor_role'])!==$viewerRole) continue; $threadId=strtolower(trim((string)($row['thread_id']??''))); if($threadId!=='') $allowedThreadIds[$threadId]=true; $messageId=wc_norm_msg_id((string)($row['message_id']??'')); if($messageId!=='') $allowedMessageIds[$messageId]=true; }
 $filtered=array_values(array_filter($data, fn($r)=>row_belongs_to_viewer_role($r,$viewerRole,$allowedThreadIds,$allowedMessageIds)));
 echo "--- $viewerRole / $componentKey ---\n"; foreach($filtered as $r){ echo ($r['direction'].' | '.$r['actor_role'].' | '.$r['subject'].' | '.$r['thread_id'])."\n"; } echo "count=".count($filtered)."\n";
}
